### ISSUE TITLE
Push documentation to RTD

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.PluggableAuthService#11]
Documentation is easier accessible when it can be read on readthedocs.io.

**Comment by dataflake** [comment]
FYI, this will/should require creating a toplevel ``docs`` folder with a Sphinx configuration and moving/converting the old ``.stx`` files from the product folder into it.

**Comment by dataflake** [comment]
This is now mostly done, see http://productspluggableauthservice.readthedocs.io/en/latest/

The only thing that doesn't work is the automatic API documentation for interface files with ``repoze.sphinx.autointerface``.
