### ISSUE TITLE
ZODB Role Manager: cannot edit roles anymore

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Products.PluggableAuthService#113]
Up to version 2.6.3 of the PAS, the ZODB Role Manager worked for me. It didn't show the edit icon in the "Roles" tab (instead it showed a "?") but I could assign and remove roles.

In versions 2.6.4 and 2.7.0, there ist now a nice looking edit icon instead of the "?", but clicking it doesn't trigger any action.

The links on the edit icon and "?" are identical: `https://myserver/pathtowebsite/acl_users/roles/manage_roles?role_id=MyRole&assign=1`

### What version of Python and Zope/Addons I am using:
- MacOS Catalina 10.15.7
- Zope 5.5.2
- Browsers
    - Chrome 104.0.5112.101 (official build) (x86_64)
    - Firefox 103.0.1 (64-bit)

**Comment by dataflake** [comment]
I cannot reproduce the issue. Clicking on the edit icon shows the "Assign role" form underneath the "Current Roles" list and I can search, add and remove principals from a role.

Versions:
- macOS Monterey 12.5.1 (latest release)
- Python 3.8
- Zope `master` (at this moment that's Zope 5.6)
- Products.PluggableAuthService `master` (at this moment that's version 2.7.0)
- Browsers
  - Firefox 104.0.2
  - Chromium 105.0.5195.52 (Official Build, ungoogled-chromium) (arm64)
  - Vivaldi 5.4.2753.47 (Stable channel) (arm64)
  - Safari 15.6.1 (17613.3.9.1.16)

**Comment by georgpfolz** [comment]
Sorry, my bad. I was checking it on my notebook, so the screen is not very large. Also as I was accustomed to a complete change in the page layout, I did not notice the change below the lower edge of my screen.
