### ISSUE TITLE
ZMI UI for dynamic groups broken

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Products.PluggableAuthService#33]
CMFCore 2.4.0b6/Plone 5.2-latest

See screenshot

![screenshot-dev zopyx de-8080-2019 03 18-11-51-36](https://user-images.githubusercontent.com/594239/54525362-599ce800-4974-11e9-929c-6b7ef46c7af6.png)

The properties of the configured dynamic group plugin instance should be displayed within the table

**Comment by icemac** [comment]
Moved to Products.PluggableAuthService.
