### ISSUE TITLE
Plone 4 ZMI: Assigning principals to a role in portal_role_manager throws an exception

### ISSUE THREAD

**Issue by batlock666** [zopefoundation/Products.PluggableAuthService#43]
Every time I try to add a principal to a role in portal_role_manager, I get the following exception:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 142, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 295, in publish_module
  Module ZPublisher.WSGIPublisher, line 229, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 57, in call_object
  Module Products.PluggableAuthService.utils, line 4, in wrapper
  Module <string>, line 4, in manage_assignRoleToPrincipals
  Module AccessControl.requestmethod, line 85, in _curried
  Module Products.PluggableAuthService.plugins.ZODBRoleManager, line 421, in manage_assignRoleToPrincipals
  Module Products.PlonePAS.plugins.role, line 69, in assignRoleToPrincipal
  Module Products.PluggableAuthService.plugins.ZODBRoleManager, line 303, in assignRoleToPrincipal
TypeError: '<' not supported between instances of 'str' and 'list'

Steps to reproduce:

1. Go to portal_role_manager.
2. Select a role.
3. Click "(Assign)".
4. Search for a principal.
5. Select the found principal.
6. Click the right arrow (->).
7. Exception!

Versions:

* Products.PluggableAuthService: 2.0b6
* Products.CMFPlone: 5.2rc3
* PlonePAS: 6.0.2

**Comment by batlock666** [comment]
After searching for the principal, I get this (check out the name of the role):

![Screenshot from 2019-05-28 11-13-16](https://user-images.githubusercontent.com/602991/58466958-08129580-813b-11e9-9350-7bfeccfee07c.png)

**Comment by dataflake** [comment]
Fixed by #44
