### ISSUE TITLE
Python 3 UnicodeDecodeError in decode_cookie().

### ISSUE THREAD

**Issue by litsol** [zopefoundation/Products.PluggableAuthService#45]
The file Products/PluggableAuthService/plugins/CookieAuthHelper.py defines a function named decode_cookie(). This function is called, in the same file, by the CookieAuthHelper class member function named extractCredentials(); which attempts to extract login and password credentials from a cookie extracted from a request. The extractCredentials() function has three try-except blocks, the first of which calls decode_cookie() and traps a binascii.Error.

We are using pas.plugin.authomatic. Somehow, a cookie is being passed to decode_cookie() via extractCredentials() that cannot be decoded into a Unicode string. This raises a UnicodeDecodeError, which is not caught by the try-except block in extractCredentials(), and Plone fails. To avoid this, at least for the moment, I have added UnicodeDecodeError to the exceptions trapped by the first try-except block.

I will try to resolve this problem in the pas.plugin.authomatic code itself, but, perhaps, uncovering this UnicodeDecodeError issue in CookieAuthHelper.py is helpful on its own. 

I forked the Products.PluggableAuthService.git repository at revision 21121d2.  We are developing on Python 5.2.0 and Python 3.6.8. If you think it worth making a pull-request, please let me know.

**Comment by icemac** [comment]
@litsol Thank you for reporting this issue. Could you please create a pull request from your changes as it is easier to think about code changes when seeing the actual code.

**Comment by litsol** [comment]
Dear Michael,

Since I posted my UnicodeDecode Error issue a Python 3 port of
pas.plugins.authomatic has appeared that works perfectly with your
PluggableAuthService. So my fix is not necessary.

With kind regards,

Michael Guravage

**Comment by icemac** [comment]
@litsol Thank you for your reply, I am closing this issue now.
