### ISSUE TITLE
Documentation for RTD does not get built / pushed /uploaded automatically

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Products.PluggableAuthService#49]
The documentation was updated yesterday ( #47 ) , and the changes were merged into master.

https://productspluggableauthservice.readthedocs.io/en/latest/index.html does not reflect the changes.

cc @dataflake - you seem to be very adept with the RTD workflow

**Comment by dataflake** [comment]
The changes are there. What exactly is the problem?

**Comment by jugmac00** [comment]
I am sorry - this was a caching issue of my browser.
