### ISSUE TITLE
Switch on Travis CI.

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.PluggableAuthService#6]
Travis CI is disabled for this package. 
It would be nice if someone with admin privileges could switch it on.

**Comment by jensens** [comment]
@hannosch, @MatthewWilkes don't one you have the permissions to do so?

**Comment by MatthewWilkes** [comment]
@jensens I do, I've flipped the switch.

**Comment by icemac** [comment]
@MatthewWilkes It works, thanks!
