### ISSUE TITLE
New release 2.5?

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Products.PluggableAuthService#75]
Can we have a new release please? Last one was in February, and there have been some good [changes](https://github.com/zopefoundation/Products.PluggableAuthService/blob/master/CHANGES.rst) since then.

**Comment by dataflake** [comment]
@mauritsvanrees Please provide me with your PyPI account and I will make you maintainer there.

**Comment by mauritsvanrees** [comment]
My personal account is `maurits`. You can also pick `plone` for the Plone Release Team.

**Comment by dataflake** [comment]
I added `plone` and the invite has gone out. Let me know when you're in, I will close this issue and you can go ahead and make releases.

**Comment by mauritsvanrees** [comment]
I didn't know you could do invites. I always just add a maintainer directly. Probably a new feature on PyPI.
I got the invite. Thanks.

I have released 2.5 on PyPI: https://pypi.org/project/Products.PluggableAuthService/2.5/

But I cannot push my changes to GitHub:

```
INFO: remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected. At least 1 approving review is required by reviewers with write access.
To github.com:zopefoundation/Products.PluggableAuthService.git
! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:zopefoundation/Products.PluggableAuthService.git'
INFO: To github.com:zopefoundation/Products.PluggableAuthService.git
* [new tag]         2.5 -> 2.5
```

Does there need to be some tweaking of permissions?

**Comment by mauritsvanrees** [comment]
PR with the release changes is here: https://github.com/zopefoundation/Products.PluggableAuthService/pull/76

**Comment by dataflake** [comment]
Pushes require:

- at lease one approved review
- successful Travis runs

I do not know why Travis seems to be stuck. I forced the PR merge.

**Comment by icemac** [comment]
> Does there need to be some tweaking of permissions?

`master` is a protected branch to prevent force pushes to it and deleting it. Additionally PR reviews are required. It seems that these settings forbid to push directly to master if you are not an administrator.

**Comment by dataflake** [comment]
Travis was stuck, that's all. The policy to require a review and Travis success should remain the same, no tweaking required.

**Comment by mauritsvanrees** [comment]
The point is that I could not push my release changes directly to master, but had to create a PR. That seems overkill.

**Comment by dataflake** [comment]
This is a normal policy setting so admins still get to see changes going to master.
