### ISSUE TITLE
Building documentation on RTD fails

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Products.PluggableAuthService#77]
See https://readthedocs.org/projects/productspluggableauthservice/builds/12080082/

It seems it could help to switch to builder to Python 3.

@dataflake You are the only maintainer of this RTD project. Could you try to fix it or add me (`icemac`) as co-maintainer?

**Comment by dataflake** [comment]
I have added you as a maintainer

**Comment by icemac** [comment]
Thank you. Switching the build to Python 3 helped.
