### ISSUE TITLE
ZODB Role Manager: Cannot remove roles in Safari

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Products.PluggableAuthService#91]
In the ZMI, I can add roles to users in Safari, although the right side select field looks weird, as it's very narrow and on the very right side of the screen:

<img width="559" alt="Bildschirmfoto 2021-04-22 um 12 10 43" src="https://user-images.githubusercontent.com/45688719/115697527-ec828a80-a363-11eb-869b-c3f095c9b2b8.png">

Removing a role from a user does not work at all in Safari. 

It's a minor inconvenience, as I can change to another browser to have it working.

### What version of Python and Zope/Addons I am using:

- Python 3.8.6 on FreeBSD 12.2
- Zope 5.1.2
- Safari 14.0.3 on Catalina

**Comment by dataflake** [comment]
@drfho Would you mind taking a look at this? I see that all those column `td` elements are of class `col-5`, which declares with 100%. If I remove that in the browser's inspector the two select field columns get equal width, but they don't fill all the row space anymore. Other browsers don't seem to mind, but Safari breaks.

**Comment by drfho** [comment]
hi @dataflake,
i cannot test Safari but I hope the change
https://github.com/zopefoundation/Products.PluggableAuthService/pull/100
looks the same in Safari now because the construction is based on flexbox an not table;

![roles_assign](https://user-images.githubusercontent.com/29705216/123862030-205fca80-d928-11eb-9a3d-7a385c4e26e9.gif)

**Comment by mauritsvanrees** [comment]
I have released the fix in 2.6.4.
Note: with the old code I could still remove roles in Safari, but I only tested with Zope 4, not 5, maybe that matters.
Anyway, with the new code it looks much nicer.
