### ISSUE TITLE
Error adding ZODB User Manager on zope5.2.1

### ISSUE THREAD

**Issue by gpzope** [zopefoundation/Products.PluggableAuthService#99]
### What I did:

After adding ZODB_User_Manager via ZMI when I click on it, it generates this error:

Sorry, a site error occurred.
zExceptions.NotFound: token - Expression: "context/@@csrf_token/token" - Filename: manage_users - Location: (line 22: col 32) - Arguments: template: here: context: container: nothing: None options: {'args': ()} root: request: modules: user: default: repeat: loop: {} target_language: None translate: .translate at 0x1099b48c0> attrs: {'type': 'hidden', 'name': 'csrf_token', 'value': 'context/@@csrf_token/token'} adding: None passwd: None updating: None browsing: True

**Comment by dataflake** [comment]
I just released version 2.6.3 with a fix for this issue.
